app:
  env: production

logging:
  level:
    root: INFO
    com:
      csxuhuan:
        gelatoni: DEBUG

spring:
  sleuth:
    sampler:
      probability: 1
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

  datasource:
    gelatoni:
      driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
      jdbc-url: ${DB_URL:jdbc:mysql://localhost:3306/gelatoni}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    ekiden:
      driver-class-name: ${EKIDEN_DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
      jdbc-url: ${EKIDEN_DB_URL:jdbc:mysql://localhost:3306/ekiden_db}
      username: ${DB_USER}
      password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 604800000

bot:
  chat-url: http://127.0.0.1:8081/internal/chat

wiki:
  api-url: https://ja.wikipedia.org/w/api.php