server.port=8080
spring.profiles.active=prod
app.env=production

# ========= Logger =========
logging.level.root=INFO
logging.level.com.csxuhuan.gelatoni=DEBUG

# = Sleuth =========
spring.sleuth.sampler.probability=1
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ========= Datasource =========
spring.datasource.gelatoni.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.gelatoni.url=${DB_URL}
spring.datasource.gelatoni.username=${DB_USER}
spring.datasource.gelatoni.password=${DB_PASSWORD}

spring.datasource.ekiden.driver-class-name=${EKIDEN_DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.ekiden.url=${EKIDEN_DB_URL}
spring.datasource.ekiden.username=${EKIDEN_DB_USER}
spring.datasource.ekiden.password=${EKIDEN_DB_PASSWORD}

# ========= JPA =========
spring.jpa.hibernate.ddl-auto=update

# ========= JWT =========
jwt.secret=${JWT_SECRET}
jwt.expiration-time=604800000

# ========= Bot =========
bot.chat-url=http://127.0.0.1:8081/internal/chat

# ========= Wikipedia =========
wiki.api-url=https://ja.wikipedia.org/w/api.py