app.env=prod
logging.level.root=INFO
logging.level.com.csxuhuan.gelatoni=DEBUG
logging.level.org.springframework.web=DEBUG

# ========= Default Datasource =========
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/gelatoni?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ========= Gelatoni Database (Primary) =========
spring.datasource.gelatoni.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.gelatoni.url=jdbc:mysql://localhost:3306/gelatoni?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.gelatoni.username=${DB_USER}
spring.datasource.gelatoni.password=${DB_PASSWORD}

# ========= Ekiden Database =========
spring.datasource.ekiden.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.ekiden.url=jdbc:mysql://localhost:3306/ekiden_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.ekiden.username=${DB_USER}
spring.datasource.ekiden.password=${DB_PASSWORD}

# ========= JWT =========
jwt.secret=${JWT_SECRET}
jwt.expiration-time=86400000