# ========= Application =========
spring.profiles.active=prod
app.env=production

server.port=8080

# ========= Logger =========
logging.level.root=INFO
logging.level.com.csxuhuan.gelatoni=DEBUG

# = Sleuth =========
spring.sleuth.sampler.probability=1
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ========= JWT =========
jwt.secret=${JWT_SECRET}
jwt.expiration-time=604800000

# ========= Bot =========
bot.chat-url=http://127.0.0.1:8081/internal/chat

# ========= Wikipedia =========
wiki.api-url=https://ja.wikipedia.org/w/api.php